
-- Team: Shaya Arya, Eduardo Melgoza, Jamil Staten

BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('DISPUTES','PAYMENTS','BOOKINGS',
                                 'PARKING_SLOTS','VEHICLES','USERS'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- TABLE: USERS
CREATE TABLE users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR2(255)  NOT NULL,
    password_hash VARCHAR2(255)  NOT NULL,
    first_name    VARCHAR2(100),
    last_name     VARCHAR2(100),
    phone         VARCHAR2(30),
    role          VARCHAR2(20)   DEFAULT 'user' NOT NULL,
    is_active     NUMBER(1)      DEFAULT 1       NOT NULL,
    created_at    DATE           DEFAULT SYSDATE,
    updated_at    DATE           DEFAULT SYSDATE,
    CONSTRAINT pk_users         PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email   UNIQUE (email),
    CONSTRAINT chk_users_role   CHECK (role IN ('user','admin')),
    CONSTRAINT chk_users_active CHECK (is_active IN (0,1))
);


-- TABLE: VEHICLE
CREATE TABLE vehicles (
    vehicle_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id      NUMBER         NOT NULL,
    plate_number VARCHAR2(20)   NOT NULL,
    make         VARCHAR2(50),
    model        VARCHAR2(50),
    color        VARCHAR2(30),
    year         NUMBER(4),
    is_active    NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at   DATE           DEFAULT SYSDATE,
    CONSTRAINT pk_vehicles        PRIMARY KEY (vehicle_id),
    CONSTRAINT uq_plate           UNIQUE (plate_number),
    CONSTRAINT fk_vehicles_user   FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_vehicle_active CHECK (is_active IN (0,1))
);

-- TABLE: PARKING_SLOTS
CREATE TABLE parking_slots (
    slot_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    slot_code  VARCHAR2(30)  NOT NULL,
    level_name VARCHAR2(30),
    zone       VARCHAR2(30),
    status     VARCHAR2(20)  DEFAULT 'active' NOT NULL,
    created_at DATE          DEFAULT SYSDATE,
    CONSTRAINT pk_slots       PRIMARY KEY (slot_id),
    CONSTRAINT uq_slot_code   UNIQUE (slot_code),
    CONSTRAINT chk_slot_status CHECK (status IN ('active','maintenance','closed'))
);

-- TABLE: BOOKINGS
CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id    NUMBER       NOT NULL,
    vehicle_id NUMBER,
    slot_id    NUMBER       NOT NULL,
    start_time DATE         NOT NULL,
    end_time   DATE         NOT NULL,
    status     VARCHAR2(20) DEFAULT 'reserved' NOT NULL,
    created_at DATE         DEFAULT SYSDATE,
    CONSTRAINT pk_bookings        PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_user   FOREIGN KEY (user_id)    REFERENCES users(user_id),
    CONSTRAINT fk_bookings_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
    CONSTRAINT fk_bookings_slot   FOREIGN KEY (slot_id)    REFERENCES parking_slots(slot_id),
    CONSTRAINT chk_booking_time   CHECK (end_time > start_time),
    CONSTRAINT chk_booking_status CHECK (status IN
        ('reserved','active','completed','cancelled','no_show','disputed'))
);

-- TABLE: PAYMENTS
CREATE TABLE payments (
    payment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    booking_id   NUMBER         NOT NULL,
    amount_cents NUMBER         NOT NULL,
    currency     CHAR(3)        DEFAULT 'USD' NOT NULL,
    status       VARCHAR2(20)   DEFAULT 'pending' NOT NULL,
    provider     VARCHAR2(30),
    provider_ref VARCHAR2(100),
    paid_at      DATE,
    created_at   DATE           DEFAULT SYSDATE,
    CONSTRAINT pk_payments          PRIMARY KEY (payment_id),
    CONSTRAINT uq_payment_booking   UNIQUE (booking_id),
    CONSTRAINT fk_payments_booking  FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    CONSTRAINT chk_payment_amount   CHECK (amount_cents > 0),
    CONSTRAINT chk_payment_status   CHECK (status IN
        ('pending','authorized','paid','failed','refunded'))
);

-- TABLE: DISPUTES
CREATE TABLE disputes (
    dispute_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    booking_id         NUMBER        NOT NULL,
    opened_by_user_id  NUMBER        NOT NULL,
    assigned_admin_id  NUMBER,
    reason             VARCHAR2(50)  NOT NULL,
    description        CLOB,
    status             VARCHAR2(20)  DEFAULT 'open' NOT NULL,
    resolution_note    CLOB,
    created_at         DATE          DEFAULT SYSDATE,
    resolved_at        DATE,
    CONSTRAINT pk_disputes         PRIMARY KEY (dispute_id),
    CONSTRAINT fk_disputes_booking FOREIGN KEY (booking_id)        REFERENCES bookings(booking_id),
    CONSTRAINT fk_disputes_opened  FOREIGN KEY (opened_by_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_disputes_admin   FOREIGN KEY (assigned_admin_id) REFERENCES users(user_id),
    CONSTRAINT chk_dispute_status  CHECK (status IN ('open','in_review','resolved','rejected'))
);


-- DUMMY DATA: USERS (3 regular users + 2 admins)
INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('alice.johnson@email.com', 'hashed_pw_001', 'Alice',   'Johnson', '555-0101', 'user');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('bob.smith@email.com',     'hashed_pw_002', 'Bob',     'Smith',   '555-0102', 'user');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('carol.white@email.com',   'hashed_pw_003', 'Carol',   'White',   '555-0103', 'user');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('admin.dave@parking.com',  'hashed_pw_004', 'Dave',    'Admin',   '555-0201', 'admin');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('admin.sara@parking.com',  'hashed_pw_005', 'Sara',    'Admin',   '555-0202', 'admin');


-- DUMMY DATA: VEHICLES (2 per user = 6 vehicles)
INSERT INTO vehicles (user_id, plate_number, make,       model,    color,   year)
VALUES (1, 'ABC-1234', 'Toyota',  'Camry',   'Blue',  2020);

INSERT INTO vehicles (user_id, plate_number, make,       model,    color,   year)
VALUES (1, 'XYZ-5678', 'Honda',   'Civic',   'White', 2019);

INSERT INTO vehicles (user_id, plate_number, make,       model,    color,   year)
VALUES (2, 'LMN-9012', 'Ford',    'Focus',   'Black', 2021);

INSERT INTO vehicles (user_id, plate_number, make,       model,    color,   year)
VALUES (2, 'QRS-3456', 'Chevrolet','Malibu', 'Red',   2018);

INSERT INTO vehicles (user_id, plate_number, make,       model,    color,   year)
VALUES (3, 'JKL-7890', 'Nissan',  'Altima',  'Silver',2022);

INSERT INTO vehicles (user_id, plate_number, make,       model,    color,   year)
VALUES (3, 'TUV-2345', 'Hyundai', 'Sonata',  'Gray',  2020);


-- DUMMY DATA: PARKING_SLOTS (6 slots across 2 levels/zones)
INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('A1-01', 'Level 1', 'Zone A', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('A1-02', 'Level 1', 'Zone A', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('B1-01', 'Level 1', 'Zone B', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('B2-01', 'Level 2', 'Zone B', 'maintenance');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('C2-01', 'Level 2', 'Zone C', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('C2-02', 'Level 2', 'Zone C', 'closed');


-- DUMMY DATA: BOOKINGS (6 bookings)
INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (1, 1, 1,
        TO_DATE('2025-03-01 08:00', 'YYYY-MM-DD HH24:MI'),
        TO_DATE('2025-03-01 10:00', 'YYYY-MM-DD HH24:MI'),
        'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (1, 2, 2,
        TO_DATE('2025-03-03 09:00', 'YYYY-MM-DD HH24:MI'),
        TO_DATE('2025-03-03 11:00', 'YYYY-MM-DD HH24:MI'),
        'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (2, 3, 3,
        TO_DATE('2025-03-05 13:00', 'YYYY-MM-DD HH24:MI'),
        TO_DATE('2025-03-05 15:00', 'YYYY-MM-DD HH24:MI'),
        'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (2, 4, 1,
        TO_DATE('2025-03-07 07:00', 'YYYY-MM-DD HH24:MI'),
        TO_DATE('2025-03-07 09:00', 'YYYY-MM-DD HH24:MI'),
        'disputed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (3, 5, 5,
        TO_DATE('2025-03-08 10:00', 'YYYY-MM-DD HH24:MI'),
        TO_DATE('2025-03-08 12:00', 'YYYY-MM-DD HH24:MI'),
        'reserved');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (3, 6, 2,
        TO_DATE('2025-03-09 14:00', 'YYYY-MM-DD HH24:MI'),
        TO_DATE('2025-03-09 16:00', 'YYYY-MM-DD HH24:MI'),
        'cancelled');


-- DUMMY DATA: PAYMENTS (one per booking)
INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (1, 1000, 'USD', 'paid',    'Stripe', TO_DATE('2025-03-01', 'YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (2, 1000, 'USD', 'paid',    'Stripe', TO_DATE('2025-03-03', 'YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (3, 1000, 'USD', 'paid',    'Stripe', TO_DATE('2025-03-05', 'YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (4, 1000, 'USD', 'refunded','Stripe', TO_DATE('2025-03-07', 'YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider)
VALUES (5, 1000, 'USD', 'pending', 'Stripe');

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (6, 1000, 'USD', 'refunded','Stripe', TO_DATE('2025-03-09', 'YYYY-MM-DD'));


-- DUMMY DATA: DISPUTES (2 disputes — one open, one in review)
INSERT INTO disputes (booking_id, opened_by_user_id, assigned_admin_id, reason, description, status)
VALUES (4, 2, 4,
        'double_charge',
        'I was charged twice for booking #4 on March 7th. Please investigate.',
        'in_review');

INSERT INTO disputes (booking_id, opened_by_user_id, reason, description, status)
VALUES (3, 2,
        'incorrect_slot',
        'The slot assigned did not match what I selected during booking.',
        'open');


-- VERIFICATION QUERIES
SELECT 'users'         AS tbl, COUNT(*) AS rows FROM users        UNION ALL
SELECT 'vehicles',              COUNT(*)        FROM vehicles      UNION ALL
SELECT 'parking_slots',         COUNT(*)        FROM parking_slots UNION ALL
SELECT 'bookings',              COUNT(*)        FROM bookings      UNION ALL
SELECT 'payments',              COUNT(*)        FROM payments      UNION ALL
SELECT 'disputes',              COUNT(*)        FROM disputes;
