-- ============================================================
-- Smart Parking Reservation System
-- Sprint 2 — Oracle Live SQL
-- Team: Shaya Arya, Eduardo Melgoza, Jamil Staten
-- ============================================================

-- Drop tables in reverse dependency order (safe re-run)
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('DISPUTES','PAYMENTS','BOOKINGS',
                                 'PARKING_SLOTS','VEHICLES','USERS'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- ============================================================
-- TABLE: USERS
-- Normalization note: All non-key attributes (email, name,
-- phone, role, is_active, timestamps) are fully dependent on
-- user_id only. No partial or transitive dependencies. In 3NF.
-- ============================================================
CREATE TABLE users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR2(255)  NOT NULL,
    password_hash VARCHAR2(255)  NOT NULL,
    first_name    VARCHAR2(100),
    last_name     VARCHAR2(100),
    phone         VARCHAR2(30),
    role          VARCHAR2(20)   DEFAULT 'user' NOT NULL,
    is_active     NUMBER(1)      DEFAULT 1       NOT NULL,
    created_at    DATE           DEFAULT SYSDATE,
    updated_at    DATE           DEFAULT SYSDATE,
    CONSTRAINT pk_users         PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email   UNIQUE (email),
    CONSTRAINT chk_users_role   CHECK (role IN ('user','admin')),
    CONSTRAINT chk_users_active CHECK (is_active IN (0,1))
);

-- ============================================================
-- TABLE: VEHICLES
-- Normalization note: All attributes depend only on vehicle_id.
-- user_id is a FK — no transitive dependency since user data
-- lives in USERS. plate_number is a candidate key. In 3NF.
-- ON DELETE: Restrict (default) — cannot delete user with vehicles.
-- ============================================================
CREATE TABLE vehicles (
    vehicle_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id      NUMBER         NOT NULL,
    plate_number VARCHAR2(20)   NOT NULL,
    make         VARCHAR2(50),
    model        VARCHAR2(50),
    color        VARCHAR2(30),
    year         NUMBER(4),
    is_active    NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at   DATE           DEFAULT SYSDATE,
    CONSTRAINT pk_vehicles        PRIMARY KEY (vehicle_id),
    CONSTRAINT uq_plate           UNIQUE (plate_number),
    CONSTRAINT fk_vehicles_user   FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_vehicle_active CHECK (is_active IN (0,1))
);

-- ============================================================
-- TABLE: PARKING_SLOTS
-- Normalization note: slot_code, level_name, zone, status all
-- depend solely on slot_id. No multi-valued or transitive deps.
-- slot_code is a candidate key. In BCNF.
-- ============================================================
CREATE TABLE parking_slots (
    slot_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    slot_code  VARCHAR2(30)  NOT NULL,
    level_name VARCHAR2(30),
    zone       VARCHAR2(30),
    status     VARCHAR2(20)  DEFAULT 'active' NOT NULL,
    created_at DATE          DEFAULT SYSDATE,
    CONSTRAINT pk_slots        PRIMARY KEY (slot_id),
    CONSTRAINT uq_slot_code    UNIQUE (slot_code),
    CONSTRAINT chk_slot_status CHECK (status IN ('active','maintenance','closed'))
);

-- ============================================================
-- TABLE: BOOKINGS
-- Normalization note: All attributes depend on booking_id.
-- user_id, vehicle_id, slot_id are FKs — user/vehicle/slot
-- attributes live in their own tables (no transitive deps here).
-- start_time and end_time are independent facts about the booking.
-- In 3NF / BCNF.
-- ON DELETE: Restrict — cannot delete a user or slot with bookings.
-- ============================================================
CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id    NUMBER       NOT NULL,
    vehicle_id NUMBER,
    slot_id    NUMBER       NOT NULL,
    start_time DATE         NOT NULL,
    end_time   DATE         NOT NULL,
    status     VARCHAR2(20) DEFAULT 'reserved' NOT NULL,
    created_at DATE         DEFAULT SYSDATE,
    CONSTRAINT pk_bookings         PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_user    FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_bookings_vehicle FOREIGN KEY (vehicle_id)
        REFERENCES vehicles(vehicle_id),
    CONSTRAINT fk_bookings_slot    FOREIGN KEY (slot_id)
        REFERENCES parking_slots(slot_id),
    CONSTRAINT chk_booking_time    CHECK (end_time > start_time),
    CONSTRAINT chk_booking_status  CHECK (status IN
        ('reserved','active','completed','cancelled','no_show','disputed'))
);

-- ============================================================
-- TABLE: PAYMENTS
-- Normalization note: All payment attributes depend on payment_id.
-- booking_id is a FK and also a candidate key (UNIQUE).
-- amount_cents, currency, status, provider, paid_at are all
-- facts about the payment itself — no transitive deps. In BCNF.
-- ON DELETE: Restrict — cannot delete a booking with a payment.
-- ============================================================
CREATE TABLE payments (
    payment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    booking_id   NUMBER         NOT NULL,
    amount_cents NUMBER         NOT NULL,
    currency     CHAR(3)        DEFAULT 'USD' NOT NULL,
    status       VARCHAR2(20)   DEFAULT 'pending' NOT NULL,
    provider     VARCHAR2(30),
    provider_ref VARCHAR2(100),
    paid_at      DATE,
    created_at   DATE           DEFAULT SYSDATE,
    CONSTRAINT pk_payments         PRIMARY KEY (payment_id),
    CONSTRAINT uq_payment_booking  UNIQUE (booking_id),
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id),
    CONSTRAINT chk_payment_amount  CHECK (amount_cents > 0),
    CONSTRAINT chk_payment_status  CHECK (status IN
        ('pending','authorized','paid','failed','refunded'))
);

-- ============================================================
-- TABLE: DISPUTES
-- Normalization note: All attributes depend on dispute_id.
-- booking_id, opened_by_user_id, assigned_admin_id are FKs.
-- No multi-valued attributes — description and resolution_note
-- are single CLOB facts per dispute. In BCNF.
-- Two FKs to users represent different roles (no violation).
-- ON DELETE: Restrict — cannot delete booking or user with disputes.
-- ============================================================
CREATE TABLE disputes (
    dispute_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    booking_id         NUMBER        NOT NULL,
    opened_by_user_id  NUMBER        NOT NULL,
    assigned_admin_id  NUMBER,
    reason             VARCHAR2(50)  NOT NULL,
    description        CLOB,
    status             VARCHAR2(20)  DEFAULT 'open' NOT NULL,
    resolution_note    CLOB,
    created_at         DATE          DEFAULT SYSDATE,
    resolved_at        DATE,
    CONSTRAINT pk_disputes         PRIMARY KEY (dispute_id),
    CONSTRAINT fk_disputes_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id),
    CONSTRAINT fk_disputes_opened  FOREIGN KEY (opened_by_user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_disputes_admin   FOREIGN KEY (assigned_admin_id)
        REFERENCES users(user_id),
    CONSTRAINT chk_dispute_status  CHECK (status IN
        ('open','in_review','resolved','rejected'))
);

-- ============================================================
-- SAMPLE DATA: USERS
-- ============================================================
INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('alice.johnson@email.com', 'hashed_pw_001', 'Alice', 'Johnson', '555-0101', 'user');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('bob.smith@email.com', 'hashed_pw_002', 'Bob', 'Smith', '555-0102', 'user');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('carol.white@email.com', 'hashed_pw_003', 'Carol', 'White', '555-0103', 'user');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('admin.dave@parking.com', 'hashed_pw_004', 'Dave', 'Admin', '555-0201', 'admin');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('admin.sara@parking.com', 'hashed_pw_005', 'Sara', 'Admin', '555-0202', 'admin');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('james.miller@email.com', 'hashed_pw_006', 'James', 'Miller', '555-0104', 'user');

INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('nina.patel@email.com', 'hashed_pw_007', 'Nina', 'Patel', '555-0105', 'user');

-- ============================================================
-- SAMPLE DATA: VEHICLES
-- ============================================================
INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (1, 'ABC-1234', 'Toyota', 'Camry', 'Blue', 2020);

INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (1, 'XYZ-5678', 'Honda', 'Civic', 'White', 2019);

INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (2, 'LMN-9012', 'Ford', 'Focus', 'Black', 2021);

INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (2, 'QRS-3456', 'Chevrolet', 'Malibu', 'Red', 2018);

INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (3, 'JKL-7890', 'Nissan', 'Altima', 'Silver', 2022);

INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (3, 'TUV-2345', 'Hyundai', 'Sonata', 'Gray', 2020);

INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (6, 'DEF-6789', 'BMW', '3 Series', 'Black', 2023);

INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (7, 'GHI-0123', 'Honda', 'Accord', 'White', 2021);

-- ============================================================
-- SAMPLE DATA: PARKING SLOTS
-- ============================================================
INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('A1-01', 'Level 1', 'Zone A', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('A1-02', 'Level 1', 'Zone A', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('B1-01', 'Level 1', 'Zone B', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('B2-01', 'Level 2', 'Zone B', 'maintenance');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('C2-01', 'Level 2', 'Zone C', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('C2-02', 'Level 2', 'Zone C', 'closed');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('A2-01', 'Level 2', 'Zone A', 'active');

INSERT INTO parking_slots (slot_code, level_name, zone, status)
VALUES ('A2-02', 'Level 2', 'Zone A', 'active');

-- ============================================================
-- SAMPLE DATA: BOOKINGS
-- ============================================================
INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (1, 1, 1,
    TO_DATE('2025-03-01 08:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-03-01 10:00','YYYY-MM-DD HH24:MI'), 'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (1, 2, 2,
    TO_DATE('2025-03-03 09:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-03-03 11:00','YYYY-MM-DD HH24:MI'), 'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (2, 3, 3,
    TO_DATE('2025-03-05 13:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-03-05 15:00','YYYY-MM-DD HH24:MI'), 'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (2, 4, 1,
    TO_DATE('2025-03-07 07:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-03-07 09:00','YYYY-MM-DD HH24:MI'), 'disputed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (3, 5, 5,
    TO_DATE('2025-03-08 10:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-03-08 12:00','YYYY-MM-DD HH24:MI'), 'reserved');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (3, 6, 2,
    TO_DATE('2025-03-09 14:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-03-09 16:00','YYYY-MM-DD HH24:MI'), 'cancelled');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (6, 7, 7,
    TO_DATE('2025-04-01 09:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-04-01 11:00','YYYY-MM-DD HH24:MI'), 'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (7, 8, 8,
    TO_DATE('2025-04-02 14:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-04-02 16:00','YYYY-MM-DD HH24:MI'), 'active');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (1, 1, 3,
    TO_DATE('2025-04-05 08:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-04-05 10:00','YYYY-MM-DD HH24:MI'), 'completed');

INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (2, 3, 5,
    TO_DATE('2025-04-06 11:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-04-06 13:00','YYYY-MM-DD HH24:MI'), 'no_show');

-- ============================================================
-- SAMPLE DATA: PAYMENTS
-- ============================================================
INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (1, 1000, 'USD', 'paid', 'Stripe', TO_DATE('2025-03-01','YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (2, 1000, 'USD', 'paid', 'Stripe', TO_DATE('2025-03-03','YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (3, 1000, 'USD', 'paid', 'Stripe', TO_DATE('2025-03-05','YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (4, 1000, 'USD', 'refunded', 'Stripe', TO_DATE('2025-03-07','YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider)
VALUES (5, 1000, 'USD', 'pending', 'Stripe');

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (6, 1000, 'USD', 'refunded', 'Stripe', TO_DATE('2025-03-09','YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (7, 1200, 'USD', 'paid', 'Stripe', TO_DATE('2025-04-01','YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider)
VALUES (8, 1200, 'USD', 'authorized', 'Stripe');

INSERT INTO payments (booking_id, amount_cents, currency, status, provider, paid_at)
VALUES (9, 1000, 'USD', 'paid', 'Stripe', TO_DATE('2025-04-05','YYYY-MM-DD'));

INSERT INTO payments (booking_id, amount_cents, currency, status, provider)
VALUES (10, 1000, 'USD', 'failed', 'Stripe');

-- ============================================================
-- SAMPLE DATA: DISPUTES
-- ============================================================
INSERT INTO disputes (booking_id, opened_by_user_id, assigned_admin_id,
    reason, description, status)
VALUES (4, 2, 4,
    'double_charge',
    'I was charged twice for booking #4 on March 7th.',
    'in_review');

INSERT INTO disputes (booking_id, opened_by_user_id, reason, description, status)
VALUES (3, 2,
    'incorrect_slot',
    'The slot assigned did not match what I selected.',
    'open');

INSERT INTO disputes (booking_id, opened_by_user_id, assigned_admin_id,
    reason, description, status, resolution_note, resolved_at)
VALUES (6, 3, 5,
    'no_refund',
    'I cancelled my booking but never received a refund.',
    'resolved',
    'Refund processed manually. Payment reversed on 2025-03-15.',
    TO_DATE('2025-03-15','YYYY-MM-DD'));

-- ============================================================
-- PART 4: CRUD QUERIES (12 real-world scenarios)
-- ============================================================

-- Q1 INSERT: New user registers
INSERT INTO users (email, password_hash, first_name, last_name, phone, role)
VALUES ('marco.rossi@email.com', 'hashed_pw_008', 'Marco', 'Rossi', '555-0106', 'user');

-- Q2 INSERT: User registers a vehicle
INSERT INTO vehicles (user_id, plate_number, make, model, color, year)
VALUES (6, 'ZZZ-9999', 'Tesla', 'Model Y', 'Red', 2024);

-- Q3 INSERT: User makes a booking
INSERT INTO bookings (user_id, vehicle_id, slot_id, start_time, end_time, status)
VALUES (6, 7, 7,
    TO_DATE('2025-05-01 10:00','YYYY-MM-DD HH24:MI'),
    TO_DATE('2025-05-01 12:00','YYYY-MM-DD HH24:MI'),
    'reserved');

-- Q4 INSERT: Payment generated for booking
INSERT INTO payments (booking_id, amount_cents, currency, status, provider)
VALUES (11, 1000, 'USD', 'pending', 'Stripe');

-- Q5 UPDATE: User updates phone number
UPDATE users
SET phone = '555-9999', updated_at = SYSDATE
WHERE user_id = 1;

-- Q6 UPDATE: Admin puts slot under maintenance
UPDATE parking_slots
SET status = 'maintenance'
WHERE slot_id = 7;

-- Q7 UPDATE: User cancels a booking
UPDATE bookings
SET status = 'cancelled'
WHERE booking_id = 5 AND user_id = 3;

-- Q8 UPDATE: Admin resolves a dispute
UPDATE disputes
SET status      = 'resolved',
    resolution_note = 'Issue confirmed. Refund issued to user.',
    resolved_at = SYSDATE
WHERE dispute_id = 2 AND assigned_admin_id IS NOT NULL;

-- Q9 DELETE: Remove a closed slot (only if no bookings)
DELETE FROM parking_slots
WHERE slot_id = 6 AND status = 'closed';

-- Q10 DELETE (soft): Deactivate a user account
UPDATE users
SET is_active = 0, updated_at = SYSDATE
WHERE user_id = 7;

-- Q11 SELECT: View user's active bookings
SELECT booking_id, slot_id, start_time, end_time, status
FROM bookings
WHERE user_id = 1
  AND status IN ('reserved','active')
ORDER BY start_time;

-- Q12 SELECT: Find unassigned open disputes
SELECT dispute_id, booking_id, opened_by_user_id, reason, created_at
FROM disputes
WHERE status = 'open'
  AND assigned_admin_id IS NULL
ORDER BY created_at;

-- ============================================================
-- PART 5: ADVANCED JOIN QUERIES (10 queries)
-- ============================================================

-- AQ1: Full booking report (user + slot)
SELECT b.booking_id,
       u.first_name || ' ' || u.last_name AS user_name,
       ps.slot_code, ps.level_name, ps.zone,
       b.start_time, b.end_time, b.status
FROM bookings b
JOIN users          u  ON b.user_id = u.user_id
JOIN parking_slots  ps ON b.slot_id  = ps.slot_id
ORDER BY b.start_time DESC;

-- AQ2: Transaction report (booking + vehicle + payment)
SELECT b.booking_id,
       u.email,
       v.plate_number,
       v.make || ' ' || v.model    AS vehicle,
       p.amount_cents / 100        AS amount_usd,
       p.status                    AS payment_status,
       p.paid_at
FROM bookings b
JOIN users    u ON b.user_id    = u.user_id
JOIN vehicles v ON b.vehicle_id = v.vehicle_id
JOIN payments p ON b.booking_id = p.booking_id
ORDER BY p.paid_at DESC NULLS LAST;

-- AQ3: Available slots for a given time window
SELECT ps.slot_id, ps.slot_code, ps.level_name, ps.zone
FROM parking_slots ps
WHERE ps.status = 'active'
  AND ps.slot_id NOT IN (
      SELECT b.slot_id FROM bookings b
      WHERE b.status NOT IN ('cancelled','completed','no_show')
        AND b.start_time < TO_DATE('2025-05-01 12:00','YYYY-MM-DD HH24:MI')
        AND b.end_time   > TO_DATE('2025-05-01 10:00','YYYY-MM-DD HH24:MI')
  )
ORDER BY ps.slot_code;

-- AQ4: Revenue per user (paid bookings only)
SELECT u.user_id,
       u.first_name || ' ' || u.last_name AS user_name,
       COUNT(p.payment_id)       AS total_bookings,
       SUM(p.amount_cents) / 100 AS total_spent_usd
FROM users u
JOIN bookings b ON u.user_id    = b.user_id
JOIN payments p ON b.booking_id = p.booking_id
WHERE p.status = 'paid'
GROUP BY u.user_id, u.first_name, u.last_name
ORDER BY total_spent_usd DESC;

-- AQ5: Dispute dashboard (opener + admin + slot)
SELECT d.dispute_id,
       op.first_name || ' ' || op.last_name  AS opened_by,
       ad.first_name || ' ' || ad.last_name  AS assigned_admin,
       ps.slot_code,
       b.start_time,
       d.reason,
       d.status
FROM disputes d
JOIN bookings      b  ON d.booking_id        = b.booking_id
JOIN users         op ON d.opened_by_user_id = op.user_id
LEFT JOIN users    ad ON d.assigned_admin_id  = ad.user_id
JOIN parking_slots ps ON b.slot_id            = ps.slot_id
ORDER BY d.created_at DESC;

-- AQ6: Most booked slots
SELECT ps.slot_code, ps.level_name, ps.zone,
       COUNT(b.booking_id) AS total_bookings
FROM parking_slots ps
JOIN bookings b ON ps.slot_id = b.slot_id
GROUP BY ps.slot_code, ps.level_name, ps.zone
ORDER BY total_bookings DESC;

-- AQ7: Users with open or in-review disputes
SELECT u.user_id,
       u.first_name || ' ' || u.last_name AS user_name,
       u.email,
       COUNT(d.dispute_id) AS open_disputes
FROM users u
JOIN bookings b ON u.user_id    = b.user_id
JOIN disputes d ON b.booking_id = d.booking_id
WHERE d.status IN ('open','in_review')
GROUP BY u.user_id, u.first_name, u.last_name, u.email
ORDER BY open_disputes DESC;

-- AQ8: Bookings with failed payments
SELECT b.booking_id,
       u.first_name || ' ' || u.last_name AS user_name,
       u.email,
       ps.slot_code,
       b.start_time,
       p.amount_cents / 100 AS amount_usd,
       p.status             AS payment_status
FROM bookings b
JOIN users         u  ON b.user_id    = u.user_id
JOIN parking_slots ps ON b.slot_id    = ps.slot_id
JOIN payments      p  ON b.booking_id = p.booking_id
WHERE p.status = 'failed'
ORDER BY b.start_time;

-- AQ9: Full booking history for user 1
SELECT b.booking_id,
       ps.slot_code, ps.zone,
       v.plate_number,
       b.start_time, b.end_time, b.status,
       p.amount_cents / 100 AS amount_usd,
       p.status             AS payment_status
FROM bookings b
JOIN parking_slots ps ON b.slot_id    = ps.slot_id
JOIN payments      p  ON b.booking_id = p.booking_id
LEFT JOIN vehicles v  ON b.vehicle_id = v.vehicle_id
WHERE b.user_id = 1
ORDER BY b.start_time DESC;

-- AQ10: Daily booking count by zone
SELECT ps.zone,
       TRUNC(b.start_time)  AS booking_date,
       COUNT(b.booking_id)  AS bookings_that_day
FROM bookings b
JOIN parking_slots ps ON b.slot_id = ps.slot_id
WHERE b.status NOT IN ('cancelled','no_show')
GROUP BY ps.zone, TRUNC(b.start_time)
ORDER BY booking_date, ps.zone;

-- ============================================================
-- CONSTRAINT VIOLATION TESTS (edge cases)
-- ============================================================

-- EC1: Duplicate email (should fail with ORA-00001)
-- INSERT INTO users (email, password_hash, role)
-- VALUES ('alice.johnson@email.com', 'pw', 'user');

-- EC2: Reversed booking time (should fail with ORA-02290)
-- INSERT INTO bookings (user_id, slot_id, start_time, end_time, status)
-- VALUES (1, 1,
--   TO_DATE('2025-05-01 10:00','YYYY-MM-DD HH24:MI'),
--   TO_DATE('2025-05-01 08:00','YYYY-MM-DD HH24:MI'), 'reserved');

-- EC3: Second payment for same booking (should fail with ORA-00001)
-- INSERT INTO payments (booking_id, amount_cents, currency, status, provider)
-- VALUES (1, 500, 'USD', 'pending', 'Stripe');

-- EC4: Invalid role value (should fail with ORA-02290)
-- INSERT INTO users (email, password_hash, role)
-- VALUES ('hacker@email.com', 'pw', 'superadmin');

-- ============================================================
-- VERIFICATION
-- ============================================================
SELECT 'users'          AS tbl, COUNT(*) AS row_count FROM users         UNION ALL
SELECT 'vehicles',               COUNT(*)             FROM vehicles       UNION ALL
SELECT 'parking_slots',          COUNT(*)             FROM parking_slots  UNION ALL
SELECT 'bookings',               COUNT(*)             FROM bookings       UNION ALL
SELECT 'payments',               COUNT(*)             FROM payments       UNION ALL
SELECT 'disputes',               COUNT(*)             FROM disputes;
